#!/bin/sh
#
# ariba-Xvfb     Start/Stop the Xvfb for Ariba
#
# chkconfig: 2345 94 06
# description: X server for Ariba

### BEGIN INIT INFO
# Provides: ariba-Xvfb
# Required-Start: $local_fs $syslog
# Required-Stop: $local_fs $syslog
# Default-Start: 2345
# Default-Stop: 90
# Short-Description: run Xvfb daemon for Ariba
# Description: The Xvfb server for Ariba
### END INIT INFO

RETVAL=0
# Source function library.
. /etc/rc.d/init.d/functions
. /etc/rc.d/init.d/functions_ariba

prog="ariba-Xvfb"
exec=/usr/bin/Xvfb
pidfile=/var/run/$prog.pid
lockfile=/var/lock/subsys/$prog
config=/etc/sysconfig/ariba

[ -e $config ] && . $config

start() {
        if [ $UID -ne 0 ] ; then
                echo "User has insufficient privilege."
                exit 4
        fi
        [ -f $pidfile ] && rm $pidfile                                          # if running, start is not called
        [ -x $exec ] || exit 5
        echo -n $"Starting $prog: "
        daemon_bg --pidfile $pidfile --wait=check_port:${XVFB_STARTUP_WAIT:-120} $exec $XVFBARGS
        retval=$?
        [ $retval -eq 0 ] && touch $lockfile
}

stop() {
        if [ $UID -ne 0 ] ; then
                echo "User has insufficient privilege."
                exit 4
        fi
        echo -n $"Stopping $prog: "
        pid="$(get_pid)"
        if [ -n "$pid" ]; then
                [ -f $pidfile ] || echo "$pid" > $pidfile
                killproc $exec
                RETVAL=3
        else
                failure $"Stopping $prog"
        fi   
        retval=$?
        echo
        [ $retval -eq 0 ] && rm -f $lockfile
}

restart() {
        rh_status_q && stop
        start
}

force_reload() {
        # new configuration takes effect after restart
        restart
}

get_pid() {
        pgrep -f "^$exec $XVFBARGS"
}

check_port() {
        pid=$(get_pid)
        [ -n "$pid" ] && {
                lsof -a -p $pid -P -i :$XVFB_PORT || {
                        echo $"Port $XVFB_PORT not opened by $pid"
                        return 1
                }
        }
}

port_status() {
        # run checks to determine if the service is running or use generic status
        proc_status && check_port
}

proc_status() {
        # run checks to determine if the service is running or use generic status
        pgrep -l -f "^$exec $XVFBARGS"
}

proc_status_q() {
        proc_status >/dev/null
}


case "$1" in
        start)
                stat_out=$(proc_status) && {
                        echo -e $"NOT Starting $prog - already running:\\n$stat_out"                         
                        exit 0
                }
                $1
                ;;
        stop)
                proc_status_q || {
                        echo $"NOT Stopping $prog - not running"                         
                        exit 0
                }
                $1
                ;;
        restart)
                $1
                ;;
        reload)
                exit 1                                                                  # reload not supported
                ;;
        force-reload)
                force_reload
                ;;
        status)
                port_status
                ;;
        condrestart|try-restart)
                proc_status_q || exit 0
                restart
                ;;
        *)
                echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
                exit 2
esac
exit $?
