-- DROP TABLESPACE sourcing INCLUDING CONTENTS AND datafiles;
-- DROP USER sourcing CASCADE;
-- DROP TABLESPACE sourcings1 INCLUDING CONTENTS AND datafiles;
-- DROP USER sourcings1 CASCADE;
-- DROP TABLESPACE sourcings2 INCLUDING CONTENTS AND datafiles;
-- DROP USER sourcings2 CASCADE;

CREATE TABLESPACE sourcing LOGGING DATAFILE '/home/oracle/db/sourcing_1.ora' SIZE 1G AUTOEXTEND ON NEXT 1024K EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
commit;

CREATE USER sourcing PROFILE DEFAULT IDENTIFIED BY sourcing DEFAULT TABLESPACE sourcing QUOTA unlimited on sourcing ACCOUNT UNLOCK;
GRANT CONNECT to sourcing;
GRANT RESOURCE TO sourcing;
GRANT CREATE TABLE TO sourcing;
GRANT CREATE ANY VIEW TO sourcing;
GRANT CREATE ANY INDEX TO sourcing;
GRANT CREATE PROCEDURE TO sourcing;
GRANT CREATE CLUSTER TO sourcing;
GRANT CREATE SESSION TO sourcing;
GRANT create sequence TO sourcing;
GRANT create trigger to sourcing;
GRANT SELECT_CATALOG_ROLE TO sourcing;

-- necessary for Free Text Search functionality
GRANT CTXAPP TO sourcing;
GRANT EXECUTE ON CTXSYS.CTX_CLS TO sourcing;
GRANT EXECUTE ON CTXSYS.CTX_DDL TO sourcing;
GRANT EXECUTE ON CTXSYS.CTX_DOC TO sourcing;
GRANT EXECUTE ON CTXSYS.CTX_OUTPUT TO sourcing;
GRANT EXECUTE ON CTXSYS.CTX_QUERY TO sourcing;
GRANT EXECUTE ON CTXSYS.CTX_REPORT TO sourcing;
GRANT EXECUTE ON CTXSYS.CTX_THES TO sourcing;
GRANT EXECUTE ON CTXSYS.CTX_ULEXER TO sourcing;

ALTER USER sourcing QUOTA UNLIMITED ON sourcing;
COMMIT;

CREATE TABLESPACE sourcings1 LOGGING DATAFILE '/home/oracle/db/sourcings1.ora' SIZE 1G AUTOEXTEND ON NEXT 1024K EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE sourcings2 LOGGING DATAFILE '/home/oracle/db/sourcings2.ora' SIZE 1G AUTOEXTEND ON NEXT 1024K EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
COMMIT;

CREATE USER sourcings1 PROFILE DEFAULT IDENTIFIED BY sourcings1 DEFAULT TABLESPACE sourcings1 QUOTA unlimited on sourcings1 ACCOUNT UNLOCK;
GRANT CONNECT to sourcings1;
GRANT RESOURCE TO sourcings1;
GRANT CREATE TABLE TO sourcings1;
GRANT CREATE ANY VIEW TO sourcings1;
GRANT CREATE ANY INDEX TO sourcings1;
GRANT CREATE PROCEDURE TO sourcings1;
GRANT CREATE CLUSTER TO sourcings1;
GRANT CREATE SESSION TO sourcings1;
GRANT SELECT_CATALOG_ROLE TO sourcings1;
GRANT CTXAPP TO sourcings1;
ALTER USER sourcings1 QUOTA UNLIMITED ON sourcings1;
COMMIT;

CREATE USER sourcings2 PROFILE DEFAULT IDENTIFIED BY sourcings2 DEFAULT TABLESPACE sourcings2 QUOTA unlimited on sourcings2 ACCOUNT UNLOCK;
GRANT CONNECT to sourcings2;
GRANT RESOURCE TO sourcings2;
GRANT CREATE TABLE TO sourcings2;
GRANT CREATE ANY VIEW TO sourcings2;
GRANT CREATE ANY INDEX TO sourcings2;
GRANT CREATE PROCEDURE TO sourcings2;
GRANT CREATE CLUSTER TO sourcings2;
GRANT CREATE SESSION TO sourcings2;
GRANT SELECT_CATALOG_ROLE TO sourcings2;
GRANT CTXAPP TO sourcings2;
ALTER USER sourcings2 QUOTA UNLIMITED ON sourcings2;
COMMIT;

EXIT;